site_name: mkdocs-toggle-sidebar-plugin
repo_url: https://github.com/six-two/mkdocs-toggle-sidebar-plugin

# theme: readthedocs

theme:
  name: material
  # name: ansible
  # extra:
  #   base_theme: material
  features:
    - content.code.copy
    - navigation.footer
    # - navigation.instant # for issue #5

plugins:
- search
- toggle-sidebar:
    async: True
    inline: False
    # inline: True
    javascript: ./toggle-sidebar.js
    show_navigation_by_default: False
    show_toc_by_default: False
    toggle_button: all
    debug: True
    # theme: material


# SEE https://squidfunk.github.io/mkdocs-material/reference/admonitions/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
