site_name: mkdocs-toggle-sidebar-plugin
repo_url: https://github.com/six-two/mkdocs-toggle-sidebar-plugin

# theme:
#   name: material
#   features:
#     - content.code.copy
#     - navigation.footer

plugins:
- search
- toggle-sidebar:
    toggle_button: toc


# SEE https://squidfunk.github.io/mkdocs-material/reference/admonitions/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
