site_name: mkdocs-toggle-sidebar-blugin

theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer

plugins:
- search
- toggle-sidebar


# SEE https://squidfunk.github.io/mkdocs-material/reference/admonitions/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
